version: '3.8'
services:
  api:
    build: ./engine_health/app
    ports:
      - "5050:5050"

  mlflow:
    restart: always
    build: ./mlflow
    ports:
      - "5000:5000"
    environment:
      MLFLOW_TRACKING_URI: http://0.0.0.0:5000
      AWS_PROFILE: ${AWS_PROFILE}
      # AWS_ACCESS_KEY_ID: your_access_key_id
      # AWS_SECRET_ACCESS_KEY: your_secret_access_key
    volumes:
      - ./models:/app/models  # Persist runs locally
      - $HOME/.aws/credentials:/home/app/.aws/credentials:xo-playground
    depends_on:
      - postgres
    command: mlflow server --backend-store-uri postgresql://mlflow_user:mlflow_password@postgres:5432/mlflow_db --default-artifact-root s3://engine-health/mlflow/ --host 0.0.0.0

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: mlflow_user
      POSTGRES_PASSWORD: mlflow_password
      POSTGRES_DB: mlflow_db
    ports:
      - "5432:5432"