name: dsa-engine-health
channels:
  - conda-forge
  - default
dependencies:
  - black
  - flake8
  - ipython
  - isort
  - jupyterlab
  - loguru
  - matplotlib
  - notebook
  - numpy
  - pandas
  - pip
  - python=3.11
  - scikit-learn
  - tqdm
  - typer
  - mamba
  - mlflow
  - ydata-profiling
  - scikit-learn
  - yellowbrick
  - dvc-s3
  - ca-certificates
  - plotly
  - xgboost
  - certifi
  - openssl
