name: dsa-engine-health
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - flake8
  - ipython
  - isort
  - jupyterlab
  - loguru
  - matplotlib
  - notebook
  - numpy
  - pandas
  - pip
  - python=3.10
  - scikit-learn
  - tqdm
  - typer
  - mamba
  - dvc-s3
  - ca-certificates
  - certifi
  - openssl
