name: dsa-engine-health
channels:
  - conda-forge
dependencies:
  - python=3.10
  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - dvc
  - dvc-s3
  - pip:
    - python-dotenv
    - awscli
    - mkdocs
    - -e .