name: Python Static Checks

on: [push]

jobs:
  static-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: github-actions
          environment-file: .github/workflows/envs/github-actions.yml
          # python-version: 3.10 # Match this with your environment.yml
          # activate-environment: dsa-engine-health
          # environment-file: ./environment.yml

      - name: Bash
        shell: bash -el {0}
        run: |
          conda info --envs
          conda list

      # - name: Install dependencies
      #   run: |
      #     make requirements

      - name: Run Static Checks
        shell: bash -el {0}
        run: |
          make lint
